/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MTBKOr1Tt9V
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "./ui/button";
import { AvatarImage, AvatarFallback, Avatar } from "./ui/avatar";
import Link from "next/link";
import { Textarea } from "./ui/textarea";
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "./ui/select";
import { Switch } from "./ui/switch";

export function chat_layout() {
	return (
		<div className="flex h-screen w-full">
			<div className="bg-white dark:bg-gray-950 border-r border-gray-200 dark:border-gray-800 w-64 p-4 flex flex-col">
				<div className="flex items-center justify-between mb-4">
					<h2 className="text-lg font-semibold">Chats</h2>
					<Button size="icon" variant="ghost">
						<PlusIcon className="h-5 w-5" />
					</Button>
				</div>
				<div className="flex-1 overflow-auto">
					<div className="space-y-2">
						<Link className="flex items-center gap-3 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors" href="#">
							<Avatar>
								<AvatarImage src="/placeholder-user.jpg" />
								<AvatarFallback>JD</AvatarFallback>
							</Avatar>
							<div className="flex-1 truncate">
								<p className="font-medium">John Doe</p>
								<p className="text-sm text-gray-500 dark:text-gray-400 truncate">Hey, how's it going?</p>
							</div>
							<div className="text-xs text-gray-500 dark:text-gray-400">12:34 PM</div>
						</Link>
						<Link className="flex items-center gap-3 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors" href="#">
							<Avatar>
								<AvatarImage src="/placeholder-user.jpg" />
								<AvatarFallback>JD</AvatarFallback>
							</Avatar>
							<div className="flex-1 truncate">
								<p className="font-medium">Jane Doe</p>
								<p className="text-sm text-gray-500 dark:text-gray-400 truncate">Did you see the new design?</p>
							</div>
							<div className="text-xs text-gray-500 dark:text-gray-400">11:22 AM</div>
						</Link>
						<Link className="flex items-center gap-3 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors" href="#">
							<Avatar>
								<AvatarImage src="/placeholder-user.jpg" />
								<AvatarFallback>JD</AvatarFallback>
							</Avatar>
							<div className="flex-1 truncate">
								<p className="font-medium">Bob Smith</p>
								<p className="text-sm text-gray-500 dark:text-gray-400 truncate">Let's discuss the project details.</p>
							</div>
							<div className="text-xs text-gray-500 dark:text-gray-400">Yesterday</div>
						</Link>
					</div>
				</div>
			</div>
			<div className="flex-1 bg-white dark:bg-gray-950 border-r border-gray-200 dark:border-gray-800 p-4 flex flex-col">
				<div className="flex items-center justify-between mb-4">
					<div className="flex items-center gap-3">
						<Avatar>
							<AvatarImage src="/placeholder-user.jpg" />
							<AvatarFallback>JD</AvatarFallback>
						</Avatar>
						<p className="font-medium">John Doe</p>
					</div>
					<div className="flex items-center gap-2">
						<Button size="icon" variant="ghost">
							<PhoneIcon className="h-5 w-5" />
						</Button>
						<Button size="icon" variant="ghost">
							<VideoIcon className="h-5 w-5" />
						</Button>
						<Button size="icon" variant="ghost">
							<MoreVerticalIcon className="h-5 w-5" />
						</Button>
					</div>
				</div>
				<div className="flex-1 overflow-auto">
					<div className="space-y-4">
						<div className="flex items-end gap-3">
							<Avatar>
								<AvatarImage src="/placeholder-user.jpg" />
								<AvatarFallback>JD</AvatarFallback>
							</Avatar>
							<div className="bg-gray-100 dark:bg-gray-800 p-3 rounded-lg max-w-[70%]">
								<p>Hey, how's it going?</p>
								<div className="text-xs text-gray-500 dark:text-gray-400 mt-1">12:34 PM</div>
							</div>
						</div>
						<div className="flex items-end gap-3 justify-end">
							<div className="bg-blue-500 text-white p-3 rounded-lg max-w-[70%]">
								<p>I'm doing great, thanks for asking!</p>
								<div className="text-xs text-gray-200 mt-1">12:35 PM</div>
							</div>
							<Avatar>
								<AvatarImage src="/placeholder-user.jpg" />
								<AvatarFallback>JD</AvatarFallback>
							</Avatar>
						</div>
						<div className="flex items-end gap-3">
							<Avatar>
								<AvatarImage src="/placeholder-user.jpg" />
								<AvatarFallback>JD</AvatarFallback>
							</Avatar>
							<div className="bg-gray-100 dark:bg-gray-800 p-3 rounded-lg max-w-[70%]">
								<p>Did you see the new design?</p>
								<div className="text-xs text-gray-500 dark:text-gray-400 mt-1">12:36 PM</div>
							</div>
						</div>
					</div>
				</div>
				<div className="mt-4">
					<Textarea className="w-full rounded-lg bg-gray-100 dark:bg-gray-800 border-none focus:ring-0" placeholder="Type your message..." />
				</div>
			</div>
			<div className="bg-white dark:bg-gray-950 border-l border-gray-200 dark:border-gray-800 w-64 p-4 flex flex-col">
				<div className="flex items-center justify-between mb-4">
					<h2 className="text-lg font-semibold">Settings</h2>
					<Button size="icon" variant="ghost">
						<XIcon className="h-5 w-5" />
					</Button>
				</div>
				<div className="flex-1 overflow-auto">
					<div className="space-y-4">
						<div>
							<h3 className="text-sm font-medium mb-2">Appearance</h3>
							<Select defaultValue="light">
								<SelectTrigger className="w-full">
									<SelectValue placeholder="Theme" />
								</SelectTrigger>
								<SelectContent>
									<SelectItem value="light">Light</SelectItem>
									<SelectItem value="dark">Dark</SelectItem>
									<SelectItem value="system">System</SelectItem>
								</SelectContent>
							</Select>
						</div>
						<div>
							<h3 className="text-sm font-medium mb-2">Notifications</h3>
							<div className="space-y-2">
								<div className="flex items-center justify-between">
									<p>Sounds</p>
									<Switch />
								</div>
								<div className="flex items-center justify-between">
									<p>Vibrate</p>
									<Switch />
								</div>
							</div>
						</div>
						<div>
							<h3 className="text-sm font-medium mb-2">Privacy</h3>
							<div className="space-y-2">
								<div className="flex items-center justify-between">
									<p>Online Status</p>
									<Switch />
								</div>
								<div className="flex items-center justify-between">
									<p>Read Receipts</p>
									<Switch />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}

function MoreVerticalIcon(props) {
	return (
		<svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
			<circle cx="12" cy="12" r="1" />
			<circle cx="12" cy="5" r="1" />
			<circle cx="12" cy="19" r="1" />
		</svg>
	);
}

function PhoneIcon(props) {
	return (
		<svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
			<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
		</svg>
	);
}

function PlusIcon(props) {
	return (
		<svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
			<path d="M5 12h14" />
			<path d="M12 5v14" />
		</svg>
	);
}

function VideoIcon(props) {
	return (
		<svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
			<path d="m22 8-6 4 6 4V8Z" />
			<rect width="14" height="12" x="2" y="6" rx="2" ry="2" />
		</svg>
	);
}

function XIcon(props) {
	return (
		<svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
			<path d="M18 6 6 18" />
			<path d="m6 6 12 12" />
		</svg>
	);
}
